version: '3'

services:
    rabbitmq:
        image: rabbitmq:3-management
        ports: 
            - "15672:15672"
            - "5672:5672"
        
    receive:
        build: ./Receive
        depends_on:
            - rabbitmq
        
    send:
        build: ./Send
        depends_on:
            - rabbitmq